language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: P/VfDPPkAlF1+Mp/uCcw1j0EgY33OPj8btagcCavXUvP12IP+aUHvqBuWAEyEqi7DthBaDmXkB8QtH+DOmLdRbYiOS9f9jdy7hKiApO0zPV4tbjKD7GIrQure4f6I3u2Al4Bb9jfYhE1gqvrkZlT9V2l3U1j2j+e/YRCx5rH2KG+sqo7w1B6hB6c/TT0cgOBMXpGy8qgmdPEyMkmtu/WYwZaCVqVzc9zrd5NUvofQpWiX0QBZ7oOL/pYc6B/uWsPxbc/DNa64qKPRNJXF+lm5o7UVeM2rUJRBdqepAjwW0U+8mFzwp+CDkLkf/JgfQpVsFTOM+En/RnNpOXtw/3+W5o+CVIIyjgerCTX/tvDpgLq+pZoDhF+ipyVa1WQznRRFYJjrU36JeuQGDyqoQlPvbEHLdy2gvn9Me47a+23CHFJTPwkrkNWzIRzOAMXxAUIUGCwmdyQf8PYFhaJu3p/WTVFGKZjnCqyN9JG01fsSid1b4nXdH0IB9B3KWqqbYePuibqADkDi1jx1Ehp5vDm1oU9Zmp6EzwldTBEloQHuizKMfhW3H9rfMDh9YbhbTpxAzUlmfN6PTqSLKVT8HdkECMwc4UwspOsSmW7Y5Sh9xldclHtqfeUDJSUMOq1M8jLRFj9Ifzge9X4qG38yzr4pQkZXAxsWjZ0dEULFTnAVvU=
